//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchestrA.Apps.MPNZ.TitleBarApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchestrA.Apps.MPNZ.TitleBarApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Navigation Breadcrumb and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string BreadcumbArea_Description {
            get {
                return ResourceManager.GetString("BreadcumbArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Close button on the title bar. Click on the Close button will close the current layout in runtime..
        /// </summary>
        public static string CanClose_Description {
            get {
                return ResourceManager.GetString("CanClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display the ViewApp Close button on the title bar. Click on the button will close the whole ViewApp in runtime..
        /// </summary>
        public static string CanCloseViewApp_Description {
            get {
                return ResourceManager.GetString("CanCloseViewApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Maximize button on the title bar..
        /// </summary>
        public static string CanMaximize_Description {
            get {
                return ResourceManager.GetString("CanMaximize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Minimize button on the title bar..
        /// </summary>
        public static string CanMinimize_Description {
            get {
                return ResourceManager.GetString("CanMinimize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string Close_App_Tooltip {
            get {
                return ResourceManager.GetString("Close_App_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while closing the layout from Title bar. {0}.
        /// </summary>
        public static string Close_ErrorFormat {
            get {
                return ResourceManager.GetString("Close_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Tooltip {
            get {
                return ResourceManager.GetString("Close_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Date and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string DateArea_Description {
            get {
                return ResourceManager.GetString("DateArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Date and Time and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string DateTimeArea_Description {
            get {
                return ResourceManager.GetString("DateTimeArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether the title bar has secondary row..
        /// </summary>
        public static string HasSecondary_Description {
            get {
                return ResourceManager.GetString("HasSecondary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Home button and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string HomeArea_Description {
            get {
                return ResourceManager.GetString("HomeArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Keyboard button and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string KeyboardArea_Description {
            get {
                return ResourceManager.GetString("KeyboardArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current language of the application..
        /// </summary>
        public static string Language_Tooltip {
            get {
                return ResourceManager.GetString("Language_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Runtime Language and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string LanguageArea_Description {
            get {
                return ResourceManager.GetString("LanguageArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn_Description {
            get {
                return ResourceManager.GetString("LogIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is logged in.
        /// </summary>
        public static string LogIn_LoggedIn_Tooltip {
            get {
                return ResourceManager.GetString("LogIn_LoggedIn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the login window..
        /// </summary>
        public static string LogIn_NotLoggedIn_Tooltip {
            get {
                return ResourceManager.GetString("LogIn_NotLoggedIn_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Login command and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string LoginArea_Description {
            get {
                return ResourceManager.GetString("LoginArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut_Description {
            get {
                return ResourceManager.GetString("LogOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while maximizing the layout from Title bar. {0}.
        /// </summary>
        public static string Maximize_ErrorFormat {
            get {
                return ResourceManager.GetString("Maximize_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize_Tooltip {
            get {
                return ResourceManager.GetString("Maximize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while minimizing the layout  from Title bar. {0}.
        /// </summary>
        public static string Minimize_ErrorFormat {
            get {
                return ResourceManager.GetString("Minimize_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize_Tooltip {
            get {
                return ResourceManager.GetString("Minimize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Navigation Title and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string NavigationTitleArea_Description {
            get {
                return ResourceManager.GetString("NavigationTitleArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font family of the text in primary area of the title bar..
        /// </summary>
        public static string PrimaryFontFamily_Description {
            get {
                return ResourceManager.GetString("PrimaryFontFamily_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size of the text in primary area of the title bar..
        /// </summary>
        public static string PrimaryFontSize_Description {
            get {
                return ResourceManager.GetString("PrimaryFontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font style of the text in primary area of the title bar..
        /// </summary>
        public static string PrimaryFontStyle_Description {
            get {
                return ResourceManager.GetString("PrimaryFontStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font weight of the text in primary area of the title bar..
        /// </summary>
        public static string PrimaryFontWeight_Description {
            get {
                return ResourceManager.GetString("PrimaryFontWeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while restoring the layout from Title bar. {0}.
        /// </summary>
        public static string Restore_ErrorFormat {
            get {
                return ResourceManager.GetString("Restore_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore_Tooltip {
            get {
                return ResourceManager.GetString("Restore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font family of the text in secondary area of the title bar..
        /// </summary>
        public static string SecondaryFontFamily_Description {
            get {
                return ResourceManager.GetString("SecondaryFontFamily_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size of the text in secondary area of the title bar..
        /// </summary>
        public static string SecondaryFontSize_Description {
            get {
                return ResourceManager.GetString("SecondaryFontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font style of the text in secondary area of the title bar..
        /// </summary>
        public static string SecondaryFontStyle_Description {
            get {
                return ResourceManager.GetString("SecondaryFontStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font weight of the text in secondary area of the title bar..
        /// </summary>
        public static string SecondaryFontWeight_Description {
            get {
                return ResourceManager.GetString("SecondaryFontWeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch User.
        /// </summary>
        public static string SwitchUser_Description {
            get {
                return ResourceManager.GetString("SwitchUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether to display Time and specify the area in title bar if it&apos;s displayed..
        /// </summary>
        public static string TimeArea_Description {
            get {
                return ResourceManager.GetString("TimeArea_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title text displayed in primary left area of the title bar..
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
    }
}
